Repository pankajkumarbij/easy-job-intern, pull requests merged in 2021-05, with the labels that each got.

#282 PR template updated
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GSSOC21, Level1

#286 added a delete student route (backend)
  server/controller/student.auth.js
  server/routes/student.js
Labels: GSSOC21, Level2

#288 Modified footer
  .eslintcache
  src/components/footer/footer.css
  src/components/footer/footer.js
Labels: GSSOC21, Level1, frontend

#289 Get Internship By Industry [Created all the pages]
  .eslintcache
  server/controller/employer.auth.js
  src/App.js
  src/components/Internships/InternshipByIndustry.js
  src/components/employer/employerSignin.js
  src/components/home/home.js
  src/components/navbar/navbar.js
Labels: GSSOC21, Level2

#292 delete employer (backend)
  server/controller/employer.auth.js
  server/routes/employer.js
Labels: GSSOC21, Level2

#299 stream and industry
  .eslintcache
  src/components/CreateNew/CreatFreshersJob.js
  src/components/CreateNew/CreateJob.js
  src/components/UpdateForm/FresherJobUpdate.js
  src/components/UpdateForm/JobUpdate.js
Labels: GSSOC21, Level2

#306 Search bookmarked internship (backend)
  server/controller/internships.js
  server/routes/student.js
Labels: GSSOC21, Level2

#311 Backend for get Jobs by grouped by location
  .eslintcache
  server/controller/jobs.js
  server/routes/general.js
Labels: GSSOC21, Level2

#307 Search bookmarked jobs+fresherJobs (backend)
  server/controller/freshersjob.js
  server/controller/jobs.js
  server/routes/student.js
Labels: GSSOC21, Level2

#322 internship group by location
  .eslintcache
  server/controller/internships.js
  src/App.js
  src/components/Internships/AllInternships.css
  src/components/Internships/InternshipsGroupedByLoction.js
  src/components/navbar/navbar.js
Labels: GSSOC21, Level2

#329 Application model (backend)
  server/models/application.js
Labels: GSSOC21, Level2

#336 Apply (backend)
  server/controller/applications.js
  server/models/application.js
  server/routes/student.js
Labels: GSSOC21, Level2

#337 added approve and reject application routes
  server/controller/applications.js
  server/routes/employer.js
Labels: GSSOC21, Level1

#338 added getPendingApplication route for student
  server/controller/applications.js
  server/routes/student.js
Labels: GSSOC21, Level2

#342 added getPendingInternships route (employer backend)
  server/controller/applications.js
  server/routes/employer.js
Labels: GSSOC21, Level2

#343 error page updated
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Error/error.png
Labels: GSSOC21, Level2

#339 added getApprovedApplications route
  server/controller/applications.js
  server/routes/student.js
Labels: GSSOC21, Level2

#340 added getRejectedApplications route
  server/controller/applications.js
  server/routes/student.js
Labels: GSSOC21, Level2

#341 added getPendingJobs route (employer)
  server/controller/applications.js
  server/routes/employer.js
Labels: GSSOC21, Level2

#347 job by location
  .eslintcache
  server/controller/jobs.js
  src/App.js
  src/components/Jobs/JobsGroupedByLocation.js
Labels: GSSOC21, Level2

#350 Made homepage responsive
  .eslintcache
  src/components/home/home.js
Labels: GSSOC21, Level2

#349 job by stream
  .eslintcache
  src/App.js
  src/components/Jobs/JobsGroupedByStream.js
Labels: GSSOC21, Level2

#355 Backend Created to get internship by company-name
  .eslintcache
  server/controller/internships.js
  server/routes/general.js
Labels: GSSOC21, Level2

#356 Backend Created to get job by company-name
  .eslintcache
  server/controller/jobs.js
  server/routes/general.js
Labels: GSSOC21, Level2

#357 Backend Created to get freshers-job by company-name
  .eslintcache
  server/controller/freshersjob.js
  server/routes/general.js
Labels: GSSOC21, Level1

#373 Made navbar responsive
  .eslintcache
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
Labels: GSSOC21, Level1

#374 added save company route
  server/controller/student.auth.js
  server/models/student.js
  server/routes/general.js
  server/routes/student.js
Labels: GSSOC21, Level1

#376 added getNotifications route
  server/controller/student_notification.js
  server/routes/student.js
Labels: GSSOC21, Level2

#377 internship notification
  server/controller/internships.js
Labels: GSSOC21, Level2

#378 job + fresher job notification
  server/controller/freshersjob.js
  server/controller/jobs.js
Labels: GSSOC21, Level2

#379 added get notification route
  server/controller/student_notification.js
  server/routes/student.js
Labels: GSSOC21, Level1

#380 created the internship card
  .eslintcache
  public/index.html
  src/components/Internships/AllInternships.js
  src/components/Internships/InternshipByIndustry.js
  src/components/Internships/InternshipByLocation.js
  src/components/Internships/InternshipByStream.js
  src/components/Internships/InternshipGroupedByStream.js
  src/components/Internships/InternshipsGroupedByIndustry.js
  src/components/Internships/InternshipsGroupedByLoction.js
  src/utils/UI/InternshipCard/InternshipCard.css
  src/utils/UI/InternshipCard/InternshipCard.js
Labels: GSSOC21, Level2

#383 Created freshersjob card and jobs card
  .eslintcache
  src/App.js
  src/components/FreshersJob/AllFresherJob.js
  src/components/FreshersJob/FresherJobsGroupedByIndustry.js
  src/components/Jobs/AllJobs.js
  src/components/Jobs/JobsGroupedByIndustry.js
  src/components/Jobs/JobsGroupedByLocation.js
  src/components/Jobs/JobsGroupedByStream.js
  src/components/navbar/navbar.js
  src/utils/UI/FresherJobCard/FresherJobCard.js
  src/utils/UI/JobsCard/JobsCard.js
Labels: GSSOC21, Level2

#386 application approval notification
  server/controller/applications.js
Labels: GSSOC21, Level1

#388 Create fresher jobs group by location
  .eslintcache
  src/App.js
  src/components/FreshersJob/FresherJobsGroupedByLocation.js
  src/components/navbar/navbar.js
Labels: GSSOC21, Level2

#390 jobs by company name
  .eslintcache
  src/App.js
  src/components/Internships/InternshipByCompany.js
  src/components/Jobs/JobsByCompanyName.js
  src/utils/UI/InternshipCard/InternshipCard.js
Labels: GSSOC21, Level2

#389 internships by company name
  .eslintcache
Labels: GSSOC21, Level2

#391 freshersjob by company
  .eslintcache
  src/App.js
  src/components/FreshersJob/FreshersJobByCompanyName.js
Labels: GSSOC21, Level1

#397 Create fresher jobs group by stream
  .eslintcache
  src/App.js
  src/components/FreshersJob/FresherJobsGroupedByStream.js
Labels: GSSOC21, Level2

#399 15
  .eslintcache
  server/controller/internships.js
  server/routes/general.js
Labels: GSSOC21, Level2

#403 frontend for company name for internships
  .eslintcache
  src/App.js
  src/components/Internships/AllInternships.css
  src/components/Internships/InternshipCompanyNames.js
Labels: GSSOC21, Level2

#405 Backend added for getting company name of jobs
  .eslintcache
  server/controller/jobs.js
  server/routes/general.js
Labels: GSSOC21, Level2

#406 Backend added for getting company name of Freshersjobs
  .eslintcache
  server/controller/freshersjob.js
  server/routes/general.js
Labels: GSSOC21, Level2

#407 added employer_notification model
  server/models/employer_notification.js
Labels: GSSOC21, Level2

#408 added notification feature for internship application
  server/controller/applications.js
  server/controller/employer_notification.js
Labels: GSSOC21, Level2

#409 added notification feature for job+fresher job application
  server/controller/applications.js
Labels: GSSOC21, Level2

#412 frontend of get companyName for Jobs
  .eslintcache
  src/App.js
  src/components/Jobs/JobCompanyName.js
Labels: GSSOC21, Level2

#413 frontend company Name for freshers job
  .eslintcache
  src/App.js
  src/components/FreshersJob/FreshersJobCompanyName.js
Labels: GSSOC21, Level2

#410 added getNotifications route
  server/controller/employer_notification.js
  server/routes/employer.js
Labels: GSSOC21, Level2

#411 added getNotication by id route
  server/routes/employer.js
Labels: GSSOC21, Level1

#417 Navbar and Routes
  .eslintcache
  src/App.js
  src/components/navbar/navbar.js
Labels: GSSOC21, Level2

#432 Student profile builder UI
  .eslintcache
  src/components/student-profile/Achievments.js
  src/components/student-profile/Education.js
  src/components/student-profile/Experience.js
  src/components/student-profile/Other.js
  src/components/student-profile/Profile.js
  src/components/student-profile/Project.js
  src/components/student-profile/Skills.js
  src/components/student-profile/Start.js
  src/components/student-profile/Volunteer.js
  src/components/student-profile/profile.css
Labels: GSSOC21, Level2

#438 bookmark internship
  .eslintcache
  src/components/Internships/AllInternships.js
  src/utils/UI/InternshipCard/InternshipCard.js
Labels: GSSOC21, Level2

#443 bookmark fresher's job corrected
  server/controller/freshersjob.js
  server/models/Freshers.js
  server/models/student.js
Labels: GSSOC21, Level1

#444 bookmark all jobs
  .eslintcache
  src/components/Jobs/AllJobs.js
  src/utils/UI/JobsCard/JobsCard.js
Labels: GSSOC21, Level2

#446 bookmark all fresher's jobs
  .eslintcache
  server/controller/freshersjob.js
  src/components/FreshersJob/AllFresherJob.js
  src/utils/UI/FresherJobCard/FresherJobCard.js
Labels: GSSOC21, Level2

#451 Backend Create fetch student details by id
  server/controller/student.auth.js
  server/routes/student.js
Labels: GSSOC21, Level2

#452 Backend to Fetch particular employer details by Id
  .eslintcache
  server/controller/employer.auth.js
  server/routes/employer.js
Labels: GSSOC21, Level2

#453 get bookmark internship
  server/controller/freshersjob.js
  server/controller/internships.js
Labels: GSSOC21, Level2

#458 Create company.js
  server/models/company.js
Labels: GSSOC21, Level2

#459 bookmark on all internships pages
  .eslintcache
  src/components/Internships/AllInternships.js
  src/utils/UI/InternshipCard/InternshipCard.js
Labels: GSSOC21, Level2

#462 added check
  server/controller/employer.auth.js
  server/models/company.js
Labels: GSSOC21, Level2

#463 added new fields to student model
  server/controller/student.auth.js
  server/models/student.js
Labels: GSSOC21, Level2

#464 added extra fields to 3 models
  server/controller/freshersjob.js
  server/controller/internships.js
  server/controller/jobs.js
  server/models/Freshers.js
  server/models/Internship.js
  server/models/Job.js
  server/models/employer.js
Labels: GSSOC21, Level2

#467 added addCompany route
  server/controller/employer.auth.js
  server/routes/employer.js
Labels: GSSOC21, Level2

#465 added fetch student profile route
  server/controller/employer.auth.js
  server/models/student.js
  server/routes/employer.js
Labels: GSSOC21, Level2

#486 search bookmark internship
  server/controller/internships.js
Labels: GSSOC21, Level2

#494 reloved errros in student.auth
  server/controller/student.auth.js
Labels: GSSOC21, Level3

#495 responsive student profile builder
  .eslintcache
  server/controller/student_notification.js
  src/components/student-profile/Education.js
  src/components/student-profile/Start.js
  src/components/student-profile/profile.css
Labels: GSSOC21, Level2

#499 backend for profile builder form
  server/controller/applications.js
  server/controller/studentProfile.js
  server/models/student.js
  server/routes/Category.js
  server/routes/student.js
Labels: GSSOC21, Level3

#500 Getting data for profile builder form and Student profile
  server/controller/studentProfile.js
  server/routes/student.js
Labels: GSSOC21, Level3

#508 Resolved Error in Other link
  .eslintcache
  src/components/UpdateForm/InternshipUpdate.js
  src/components/student-profile/Profile.js
  src/components/student-profile/Start.js
Labels: GSSOC21, Level2

#506 Validation, error handling and on change handler for General section in Profile builder page.
  .eslintcache
  src/components/UpdateForm/InternshipUpdate.js
  src/components/student-profile/Profile.js
  src/components/student-profile/Start.js
Labels: GSSOC21

#501 modified delete job route
  server/controller/jobs.js
  server/models/student.js
Labels: GSSOC21, Level2

#504 added view company route
  server/controller/student.auth.js
  server/routes/student.js
Labels: GSSOC21, Level2

#503 modified delete fresher job route
  server/controller/freshersjob.js
Labels: GSSOC21, Level2

#502 modified delete internship route
  server/controller/internships.js
Labels: GSSOC21, Level2

#510 general other links
  .eslintcache
  src/components/student-profile/Profile.js
  src/components/student-profile/Start.js
Labels: GSSOC21, Level2

#512 student login signup errors
  server/controller/student.auth.js
  server/models/student.js
Labels: GSSOC21, Level2

#513 Create Student Details Update Form
  server/controller/student.auth.js
  src/App.js
  src/components/student/StudentUpdateForm.js
Labels: GSSOC21, Level2

#514 Create update employer details form
  .eslintcache
  server/controller/employer.auth.js
  src/App.js
  src/components/employer/EmployerUpdateForm.js
Labels: GSSOC21, Level2

#516 Update company
  server/controller/employer.auth.js
  server/routes/employer.js
Labels: GSSOC21, Level3

#522 Validation, error handling and on change handler for Education section in Profile builder page
  .eslintcache
  src/components/student-profile/Education.js
  src/components/student-profile/Profile.js
  src/components/student-profile/Start.js
Labels: GSSOC21, Level2

#524 Validation, error handling and on change handler for Experience section in Profile builder page
  .eslintcache
  src/components/student-profile/Experience.js
  src/components/student-profile/Profile.js
Labels: GSSOC21, Level2

#526 Validation, error handling and on change handler for Project section in Profile builder page
  .eslintcache
  src/components/student-profile/Profile.js
  src/components/student-profile/Project.js
Labels: GSSOC21, Level2

#528 Validation, error handling and on change handler for Skill section in Profile builder page #527
  .eslintcache
  src/components/student-profile/Profile.js
  src/components/student-profile/Skills.js
Labels: GSSOC21, Level2

#530 Validation, error handling and on change handler for Achievements section in Profile builder page
  .eslintcache
  src/components/student-profile/Achievments.js
  src/components/student-profile/Profile.js
Labels: GSSOC21, Level2

#532 Validation, error handling and on change handler for Volunteer section in Profile builder page
  .eslintcache
  src/components/student-profile/Profile.js
  src/components/student-profile/Volunteer.js
Labels: GSSOC21, Level2

#535 Created the employer dashboard
  server/controller/employer.auth.js
  src/App.js
  src/components/employer/EmployerProfileScreen.css
  src/components/employer/EmployerProfileScreen.js
  src/components/employer/EmployerUpdateForm.js
  src/components/navbar/navbar.js
Labels: GSSOC21, Level3

#540 profile page
  .eslintcache
  server/models/student.js
  src/App.js
  src/components/student-profile/Profile.js
  src/components/student-profile/Start.js
  src/components/student-profile/StudentProfile/ProfileView.js
  src/components/student-profile/StudentProfile/components/General.js
  src/components/student-profile/profile.css
Labels: GSSOC21, Level3

#541 modify create internship route
  server/controller/internships.js
Labels: GSSOC21, Level3

#542 modify create job route
  server/controller/jobs.js
Labels: GSSOC21, Level3

#543 modify create fresher job route
  server/controller/freshersjob.js
Labels: GSSOC21, Level2

#544 added view company route
  server/controller/employer.auth.js
  server/routes/employer.js
Labels: GSSOC21, Level2

#546 Education
  .eslintcache
  server/controller/studentProfile.js
  src/components/student-profile/StudentProfile/ProfileView.js
  src/components/student-profile/StudentProfile/components/Education.js
Labels: GSSOC21, Level3

#548 Experience
  src/components/student-profile/Education.js
  src/components/student-profile/StudentProfile/ProfileView.js
  src/components/student-profile/StudentProfile/components/Education.js
  src/components/student-profile/StudentProfile/components/Experience.js
Labels: GSSOC21, Level3

#549 project
  .eslintcache
  src/components/student-profile/StudentProfile/ProfileView.js
  src/components/student-profile/StudentProfile/components/Project.js
Labels: GSSOC21, Level3
