Repository pankajkumarbij/easy-job-intern, pull requests merged in 2021-07, with the labels that each got.

#556 added badges with links in README
  README.md
Labels: LGMSOC21, Level2

#557 Alignment of the first line in "Internship By Industry, location,stream and training"
  src/components/home/home.js
Labels: Level1, PSOC21

#561 changes card design
  public/images/intern.PNG
  src/components/home/home.js
Labels: Level2, PSOC21

#564 Updated Tech Stack
  README.md
Labels: Level1, PSOC21

#567 PSOC logo added in the readme file
  README.md
  readme_assets/psoc.PNG
Labels: Level1, PSOC21

#570 README Updated
  README.md
Labels: :yellow_square: Level1, LGMSOC21

#568 Redesigned the navigation bar
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
Labels: Level2, PSOC21

#571 improved navigation bar
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
Labels: Level2, PSOC21
