Repository pankajkumarbij/easy-job-intern, pull requests merged in 2021-03, with the labels that each got.

#41 Readme fix
  README.md
Labels: good first issue

#38 Added Contributors image
  README.md
Labels: crossWoc, good first issue

#42 changed about page design and made responsive
  .eslintcache
  server/package-lock.json
  src/components/AboutUs.css
  src/components/AboutUs.js
  src/components/contactUs.css
  src/components/contactUs.js
  src/components/navbar.js
Labels: crossWoc, difficulty: easy, frontend

#45 Update README.md
  README.md
Labels: good first issue

#46 improved design of contact us page
  .eslintcache
  src/components/contactUs.css
  src/components/contactUs.js
Labels: difficulty: easy, frontend

#48 Navbar updated
  .eslintcache
  package-lock.json
  package.json
  src/App.css
  src/components/home.css
  src/components/home.js
  src/components/navbar.js
Labels: GSSOC, difficulty: medium

#51 Integrated ContactUs page with the database
  .eslintcache
  package-lock.json
  package.json
  server/api/User.js
  server/index.js
  server/models/ContactUsForm.js
  server/package-lock.json
  server/package.json
  src/components/contactUs.js
Labels: crossWoc, difficulty: medium, frontend

#54 Updated README
  README.md
Labels: GSSOC, good first issue

#62 connected AboutUs footer link to AboutUs page and refactored react-router dom code
  .eslintcache
  src/App.js
  src/components/footer/footer.js
  src/components/navbar/navbar.js
Labels: GSSOC, difficulty: easy

#65 Added Privacy Policy link in footer
  src/components/footer/footer.js
Labels: GSSOC, difficulty: easy

#64 connect terms and condition link to button
  .eslintcache
  src/components/footer/footer.js
Labels: GSSOC, difficulty: easy

#69 Added Login and Signup modals and routes and Integrated with react
  package.json
  server/index.js
  server/keys.js
  server/models/student.js
  server/package-lock.json
  server/package.json
  server/routes/contact-us.js
  server/routes/student.js
  src/components/student/login.js
  src/components/student/register.js
Labels: GSSOC

#73 connected database to contact
  .eslintcache
  server/routes/contact-us.js
  src/App.css
  src/App.js
  src/components/contact-us/contact-us.js
Labels: GSSOC, difficulty: medium

#77 Modified .GitIgnore file
  .gitignore
  package.json
Labels: GSSOC, difficulty: easy

#81 Linked the contact us page
  src/components/footer/footer.js
Labels: GSSOC, difficulty: easy

#87 Enable the contact us form submissions through formspree
  server/index.js
  server/models/contact-us-model.js
  server/package-lock.json
  server/routes/contact-us.js
  src/components/contact-us/contact-us.css
  src/components/contact-us/contact-us.js
Labels: GSSOC21, difficulty: hard

#89 Modified mentor banner, added gif
  README.md
  readme_assets/banner.png
  readme_assets/easy-job-intern-about.gif
  readme_assets/p1.jfif
  readme_assets/p2.jfif
  readme_assets/p3.jfif
Labels: GSSOC21, difficulty: medium

#91 Added the email.js file for sending mail whenever a new user signs up
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/routes/student.js
  server/utils/email.js
Labels: GSSOC21, difficulty: medium

#95 Signout
  .gitignore
  src/components/navbar/navbar.js
  src/components/student/login.js
Labels: GSSOC21, level2

#100 Added form validation to login and signup form
  src/components/student/login.js
  src/components/student/register.css
  src/components/student/register.js
  src/utils/checkValidation.js
Labels: GSSOC21, level1

#99 Enhanced user experience with bug fixes, code enhancements and more.
  public/images/favicon.ico
  public/images/logo.png
  public/index.html
  public/manifest.json
  src/components/home/home.css
  src/components/home/home.js
  src/components/student/login.js
Labels: GSSOC21, level1

#110 Removed body parser dependency
  server/index.js
  server/package.json
Labels: GSSOC21, Level1

#112 added validation in contact us form
  src/components/contact-us/contact-us.css
  src/components/contact-us/contact-us.js
Labels: GSSOC21, Level2

#116 Designed employer signup & login page
  src/App.js
  src/components/employer/employerSignin.js
  src/components/employer/employerSignup.js
  src/components/navbar/navbar.js
Labels: crossWoc, difficulty: medium, frontend

#119 Improved the design of student signup & signin page
  src/components/student/login.js
  src/components/student/register.js
Labels: crossWoc, difficulty: medium, frontend

#122 Create a Slider in Main Section (Home) #109
  package-lock.json
  public/images/Slider1.jpg
  public/images/Slider2.jpg
  public/images/Slider3.jpg
  server/package-lock.json
  src/components/home/home.js
  src/components/imgeslider/slider.css
  src/components/imgeslider/slider.js
Labels: GSSOC21, Level2

#129 Added the category model and create the routes
  server/index.js
  server/models/Category.js
  server/package-lock.json
  server/package.json
  server/routes/Category.js
Labels: GSSOC21, Level3

#131 Responsive Footer
  .eslintcache
  src/components/footer/footer.css
  src/components/footer/footer.js
Labels: GSSOC21, Level2

#134 type value edited of signup forms
  src/components/employer/employerSignup.js
  src/components/student/register.js
Labels: GSSOC21, Level1

#136 Issue #115 : Adding authentication middleware
  package-lock.json
  server/middleware/auth_employer.js
  server/middleware/auth_student.js
  server/models/employer.js
  server/models/student.js
  server/package-lock.json
  server/routes/employer.js
  server/routes/student.js
Labels: GSSOC21, Level3, backend

#137 Made the signup and login form for students mobile responsive and added the form validations for both.
  .eslintcache
  package-lock.json
  server/package-lock.json
  src/components/student/login.js
  src/components/student/register.css
  src/components/student/register.js
Labels: GSSOC21, Level2

#138 PR template update
  .github/PR_template.md
Labels: GSSOC21, Level0

#141 Made employer login and signup form responsive
  .eslintcache
  src/components/employer/employer.css
  src/components/employer/employerSignin.js
  src/components/employer/employerSignup.js
Labels: GSSOC21, Level2

#140 Update student profile route
  server/routes/student.js
Labels: GSSOC21, Level2

#148 Logout routes
  server/routes/employer.js
  server/routes/student.js
Labels: GSSOC21, Level1

#153 added controller folder
  server/controller/employer/employer.auth.js
  server/controller/student.auth.js
  server/package-lock.json
  server/routes/employer.js
  server/routes/student.js
Labels: GSSOC21, Level2

#152 style of about us page updated
  public/images/32.-Discussion.png
  public/images/INTERN SHIP (1).png
  public/images/INTERN SHIP.png
  public/images/JOB - Logo - Google Chrome 27-03-2021 19_58_07 (2).png
  src/components/about-us/about-us.css
  src/components/about-us/about-us.js
Labels: GSSOC21, Level2

#154 Added the complete form Validations for both Employer SignIn and SignIn
  package-lock.json
  src/components/employer/employerSignin.js
  src/components/employer/employerSignup.js
Labels: GSSOC21, Level3, frontend

#158 Added a 404 page
  src/App.js
  src/components/Error.css
  src/components/Error.js
Labels: GSSOC21, Level1
