Repository pankajkumarbij/easy-job-intern, pull requests merged in 2021-04, with the labels that each got.

#160 updated contributing.md
  contributing.md
Labels: GSSOC21, Level1

#164 Employee login and error message size
  .eslintcache
  package-lock.json
  server/controller/employer.auth.js
  server/package-lock.json
  src/components/Error/Error.css
  src/components/employer/employerSignin.js
Labels: GSSOC21, Level2

#168 toast and redirection to login
  .eslintcache
  package-lock.json
  package.json
  server/controller/student.auth.js
  src/components/employer/employerSignin.js
  src/components/employer/employerSignup.js
  src/components/student/login.js
  src/components/student/register.js
Labels: GSSOC21, Level1

#169 navbar create and new internship form
  .eslintcache
  src/App.js
  src/components/CreateNew/CreateInternship.js
  src/components/navbar/navbar.js
Labels: GSSOC21, Level3

#171 Created New job form
  .eslintcache
  src/App.js
  src/components/CreateNew/CreateJob.js
  src/components/navbar/navbar.js
Labels: GSSOC21, Level3

#174 Access Rights
  .eslintcache
  src/App.js
  src/components/employer/employerSignin.js
  src/components/navbar/navbar.js
  src/components/student/login.js
  src/reducers/userReducer.js
Labels: GSSOC21, Level2

#185 All internship page, start & end date , duration
  .eslintcache
  server/controller/internships.js
  server/models/Internship.js
  src/App.js
  src/components/CreateNew/CreateInternship.js
  src/components/Internships/AllInternships.css
  src/components/Internships/AllInternships.js
Labels: GSSOC21, Level3

#184 added animation to single links
  .DS_Store
  .eslintcache
  package-lock.json
  package.json
  server/.DS_Store
  server/package-lock.json
  src/.DS_Store
  src/App.js
  src/components/home/home.css
  yarn.lock
Labels: GSSOC21, Level1

#189 Internship connecting
  .DS_Store
  .eslintcache
  package-lock.json
  package.json
  server/.DS_Store
  server/controller/internships.js
  server/index.js
  server/package-lock.json
  server/routes/employer.js
  server/routes/general.js
  src/.DS_Store
  src/App.js
  src/components/Internships/AllInternships.js
  src/components/home/home.css
  yarn.lock
Labels: GSSOC21, Level2

#195 Separate functions
  server/controller/employer.auth.js
  server/controller/student.auth.js
  server/models/employer.js
  server/models/student.js
  server/routes/student.js
Labels: GSSOC21, Level1

#209 Remove warings from console
  .eslintcache
  package-lock.json
  server/package-lock.json
  src/App.js
  src/components/FreshersJob/AllFresherJob.js
  src/components/Internships/AllInternships.js
  src/components/Jobs/AllJobs.js
  src/components/about-us/about-us.js
  src/components/contact-us/contact-us.js
  src/components/employer/employerSignin.js
  src/components/employer/employerSignup.js
  src/components/footer/footer.js
  src/components/home/home.js
  src/components/navbar/navbar.js
  src/components/student/login.js
  src/components/student/register.js
Labels: GSSOC21, Level1

#211 Updating internship Backend and Connected to frontend
  .eslintcache
  server/controller/internships.js
  server/routes/employer.js
  src/components/UpdateForm/InternshipUpdate.js
Labels: GSSOC21, Level2

#213 Added initial values to update internship form
  .eslintcache
  server/controller/internships.js
  server/routes/employer.js
  src/components/Internships/AllInternships.js
  src/components/UpdateForm/InternshipUpdate.js
Labels: GSSOC21, Level1

#223 update job backend and error
  .eslintcache
  server/controller/internships.js
  server/controller/jobs.js
  server/routes/employer.js
  src/components/Internships/AllInternships.js
  src/components/Jobs/AllJobs.js
  src/components/UpdateForm/JobUpdate.js
  src/components/student/login.js
  src/components/student/register.js
Labels: GSSOC21, Level2

#224 added hover effect on icons
  .eslintcache
  src/components/footer/footer.css
  src/components/footer/footer.js
Labels: GSSOC21, Level1

#231 delete internship [backend + frotend]
  .eslintcache
  server/controller/internships.js
  server/routes/employer.js
  src/components/Internships/AllInternships.css
  src/components/Internships/AllInternships.js
Labels: GSSOC21, Level2

#235 deleting job
  .eslintcache
  server/controller/jobs.js
  server/routes/employer.js
  src/components/Internships/AllInternships.js
  src/components/Jobs/AllJobs.js
Labels: GSSOC21, Level2

#236 Delete freshers Job
  .eslintcache
  server/controller/freshersjob.js
  server/controller/jobs.js
  server/routes/employer.js
  src/components/FreshersJob/AllFresherJob.js
Labels: GSSOC21, Level2

#240 resolved
  src/utils/checkValidation.js
Labels: GSSOC21, Level1

#241 Search internship backend (employer)
  server/controller/internships.js
  server/routes/employer.js
Labels: GSSOC21, Level2

#225 Search filter applied for jobs and internships
  server/controller/freshersjob.js
  server/controller/internships.js
  server/controller/jobs.js
  server/routes/student.js
Labels: GSSOC21, Level2

#242 Search job backend (employer)
  server/controller/freshersjob.js
  server/controller/jobs.js
  server/routes/employer.js
Labels: GSSOC21, Level2

#244 Student Profile Builder (issue #98)
  .eslintcache
  package.json
  src/App.js
  src/components/student-profile/Achievments.js
  src/components/student-profile/Education.js
  src/components/student-profile/Experience.js
  src/components/student-profile/Input.js
  src/components/student-profile/Label.js
  src/components/student-profile/Other.js
  src/components/student-profile/Profile.js
  src/components/student-profile/Project.js
  src/components/student-profile/Skills.js
  src/components/student-profile/Start.js
  src/components/student-profile/Volunteer.js
  src/components/student-profile/profile.css
Labels: GSSOC21, Level3, frontend

#249 Resolved errors
  .eslintcache
  server/controller/freshersjob.js
  server/controller/internships.js
  server/controller/jobs.js
  server/routes/employer.js
  src/App.js
  src/components/UpdateForm/FresherJobUpdate.js
  src/components/UpdateForm/JobUpdate.js
Labels: GSSOC21, Level2

#252 improved text
  server/controller/employer.auth.js
Labels: GSSOC21, Level0

#256 getting intern by location
  .eslintcache
  server/controller/internships.js
  server/routes/general.js
Labels: GSSOC21, Level2

#254 New fields
  server/controller/freshersjob.js
  server/controller/internships.js
  server/controller/jobs.js
  server/models/Freshers.js
  server/models/Internship.js
  server/models/Job.js
  src/components/CreateNew/CreatFreshersJob.js
  src/components/CreateNew/CreateInternship.js
  src/components/CreateNew/CreateJob.js
Labels: GSSOC21, Level2

#264 auto label added
  .github/workflows/autolabel-pr.yml
  .github/workflows/issue-label.yaml
Labels: GSSOC21, Level1

#261 Signup verification
  .eslintcache
  package-lock.json
  package.json
  server/controller/employer.auth.js
  server/controller/student.auth.js
  server/keys.js
  server/models/employer.js
  server/models/student.js
  server/package.json
  server/routes/employer.js
  server/routes/student.js
  server/utils/signup-email.js
  server/utils/signupEmployer-email.js
  src/App.js
  src/components/employer/employerSignup.js
  src/components/welcomeSignup/welcomeSignup.js
  src/components/welcomeSignup/welcomeSignupEmployer.js
Labels: GSSOC21, Level2

#266 industry and stream
  .eslintcache
  server/controller/internships.js
  server/models/Internship.js
  src/components/CreateNew/CreateInternship.js
  src/components/Internships/AllInternships.css
  src/components/Internships/AllInternships.js
  src/components/Internships/InternshipByLocation.js
  src/components/UpdateForm/InternshipUpdate.js
Labels: GSSOC21, Level2

#273 greeting action added
  .github/workflows/greetings.yml
Labels: GSSOC21, Level1

#274 bookmark internships (backend)
  server/controller/internships.js
  server/models/Internship.js
  server/routes/student.js
Labels: GSSOC21, Level2

#276 bookmark job/fresherJob (backend)
  server/controller/freshersjob.js
  server/controller/jobs.js
  server/models/Freshers.js
  server/models/Job.js
  server/routes/student.js
Labels: GSSOC21, Level2

#279 added get internships route
  server/controller/internships.js
  server/routes/student.js
Labels: GSSOC21, Level2

#281 fetch bookmarked jobs/fresher jobs (backend)
  server/controller/freshersjob.js
  server/controller/jobs.js
  server/routes/student.js
Labels: GSSOC21, Level2
