Repository pankajkumarbij/easy-job-intern, pull requests merged in 2021-02, with the labels that each got.

#16 Added a single command to run server with client together.
  .eslintcache
  package-lock.json
  package.json
Labels: crossWoc, difficulty: easy

#17 Added new Footer
  .eslintcache
  src/App.js
  src/components/Footer.css
  src/components/Footer.js
Labels: crossWoc, difficulty: medium, frontend

#20 added new logo
  .DS_Store
  public/.DS_Store
  public/logo.png
Labels: crossWoc, difficulty: medium

#21 Fix #14 : added About Us page
  .eslintcache
  public/images/desktop.png
  public/images/inspiration.png
  public/images/puzzle.png
  public/images/read.png
  public/images/studying.png
  public/images/texture.png
  public/images/website-content.svg
  src/App.js
  src/components/AboutUs.css
  src/components/AboutUs.js
Labels: crossWoc, difficulty: easy, frontend

#24 Created Login In and Registration Form
  .eslintcache
  package-lock.json
  package.json
  src/App.js
  src/components/login.js
  src/components/navbar.js
  src/components/register.css
  src/components/register.js
Labels: crossWoc, difficulty: medium, frontend

#23 Fix #22: added logo
  .eslintcache
  public/logo.png
  src/components/navbar.js
Labels: crossWoc, difficulty: easy

#27 Fix #25: Privacy policy page
  package-lock.json
  src/App.js
  src/components/PrivacyPolicy.js
Labels: crossWoc, difficulty: easy

#28 Designed home page
  .eslintcache
  public/images/industry.png
  public/images/location.png
  public/images/ot2.png
  public/images/stream.png
  public/index.html
  src/App.js
  src/components/home.css
  src/components/home.js
Labels: crossWoc, difficulty: medium

#29 Fix #26: added terms and condition page
  .eslintcache
  src/App.js
  src/components/TermsAndCondition.js
Labels: crossWoc, difficulty: easy

#31 Updated Contributing.md
  contributing.md
  public/images/ContributionBranch.jpg
  public/images/ContributionFork.jpg
  public/images/ContributionIsssues.jpg
  public/images/ContributionPR.jpg
Labels: crossWoc, difficulty: easy

#30 Added contact us page
  .eslintcache
  src/App.js
  src/components/contactUs.css
  src/components/contactUs.js
  src/components/navbar.js
Labels: crossWoc, difficulty: easy

#39 interactive login signup
  .eslintcache
  src/App.css
  src/components/login.js
  src/components/register.css
  src/components/register.js
Labels: crossWoc, difficulty: medium, frontend
